name: Push README to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/readme.yaml

env:
  dockerpushrm_version: "1.7.0"

jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Login DockerHub
        id: dockerLogin
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_BOT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BOT_TOKEN }}

      - name: push README to Dockerhub
        run: |
          wget https://github.com/christian-korneck/docker-pushrm/releases/download/v${dockerpushrm_version}/docker-pushrm_linux_amd64
          mkdir -p $HOME/.docker/cli-plugins/
          mv docker-pushrm_linux_amd64 $HOME/.docker/cli-plugins/docker-pushrm
          chmod +x $HOME/.docker/cli-plugins/docker-pushrm
          docker pushrm danopstech/starlink_exporter --file "./README.md" --short "${{ github.event.repository.description }}"
